### ISSUE TITLE
Determine Compendium Packs for C&C System

### ISSUE THREAD

**Issue by switchspan** [switchspan/foundryvtt-cnc#1]
Determine the Compendium Packs needed for the C&C System. See: https://foundryvtt.com/article/compendium/

**Comment by HiHo01** [comment]
Is this a discussion with TLG as to what compendium packs we can include?
Are they happy for us to reproduce everything required to make and populate a character sheet?
Inventory, Spells, Abilities, Experience tables etc?

**Comment by switchspan** [comment]
Yes. I looked at the Compendium Packs for D&D 5e system and there is quite a bit in there. The equivalent would be to add the C&C Monsters and Treasure content. Not sure TLG would be good with that as it is one of their products. For the character sheet, I think they would be fine with anything that is in the Player's Handbook (PHB) -- as they have released a copy for free over the pandemic. I think we go with what is in the PHB and table working on anything extra in the compendium packs unless we get permission from TLG. Who knows -- maybe in the future we can do a joint project where they can sell digital content for Foundry (like Fantasy Grounds) when Foundry adds some digital rights management for the modules/systems.

**Comment by HiHo01** [comment]
Any correspondence from TLG on their plans?

**Comment by switchspan** [comment]
> Any correspondence from TLG on their plans?

No. I haven't heard anything yet. And haven't see anything on Discord, so I am continuing with the character sheet. Once I push that out, I will reach out to them to see where they are at with their FoundryVTT products.

**Comment by switchspan** [comment]
moving effort to the TLG repo: https://gitlab.com/troll-lord/foundry-vtt/ruleset/castles-and-crusades
