### ISSUE TITLE
Creature Sizes in config.js

### ISSUE THREAD

**Issue by Levendor68** [switchspan/foundryvtt-cnc#3]
Easy little one here... line 141 begins  5e creature sizes. 5e lists 6 sizes. CnC M&T is very consistent with only 3 sizes: small, medium, and large (MT5 p9  (Monsters & Treasure 5th printing Page 9)). Don't know whether the extras will matter if left in. Just happened to jot down the line number when scanning the file this AM.

**Comment by switchspan** [comment]
Done. I updated config.js and entity.js. I will check through the other code to make sure there are no other references. I think this is tied to the tokens as well...

**Comment by switchspan** [comment]
This is available in v0.0.23
