### ISSUE TITLE
Consider automatization taking advantage of existing 5e modules

### ISSUE THREAD

**Issue by cal413** [switchspan/foundryvtt-cnc#4]
As the base for the game system is the 5e's it would be a cool thing if we can use modules like Dynamic Active Effects or CUB for some automatization.
Maybe putting some maths like autocalculate AC would be more interesting directly in the game system, I don't know.

**Comment by switchspan** [comment]
> As the base for the game system is the 5e's it would be a cool thing if we can use modules like Dynamic Active Effects or CUB for some automatization.
> Maybe putting some maths like autocalculate AC would be more interesting directly in the game system, I don't know.

I will have to check on that -- it looks like some of the underpinnings for the SEIGE engine are just different enough that we might run into some trouble with that.

**Comment by switchspan** [comment]
moving effort to the TLG repo: https://gitlab.com/troll-lord/foundry-vtt/ruleset/castles-and-crusades
